-- Usipel PWA: Supabase Initial Schema
-- Copie e cole este código no SQL Editor do seu projeto Supabase

-- 1. Criação da tabela de Clientes (CRM Básico)
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    telefone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criação da tabela de Pedidos
CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE RESTRICT,
    descricao_caixa TEXT NOT NULL,
    medida_comprimento TEXT,
    medida_largura TEXT,
    medida_altura TEXT,
    quantidade TEXT NOT NULL,
    tipo_material TEXT,
    tem_logomarca BOOLEAN DEFAULT FALSE,
    prazo_entrega TEXT,
    status TEXT DEFAULT 'novo_pedido',
    observacoes TEXT,
    is_recorrente INTEGER DEFAULT 0,
    frequencia TEXT DEFAULT 'Mensal',
    arquivado INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) - Por enquanto permitimos TUDO (Modo Anonimo), 
-- configuraremos as regras reais na Fase 4, mas é bom já ligar
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;

-- Politicas Temporárias (Permitir CRUD publico enquanto testamos o Web App)
CREATE POLICY "Public Access Clientes" ON public.clientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Access Pedidos" ON public.pedidos FOR ALL USING (true) WITH CHECK (true);
